version: '2'

vars:
  GIT_COMMIT: { sh: git rev-parse --short HEAD }

tasks:
  build:
    desc: Build the go binary.
    deps: [build-api]

  build-api:
    desc: Build the api binary.
    cmds:
      - go build -o bin/bibliotheca -v -i cmd/bibliotheca/main.go
    sources:
      - ./*.go
    generates:
      - bin/bibliotheca{{exeExt}}

  build-container:
    desc: Build the application containers.
    cmds:
      - docker build -f deployments/Dockerfile --target app       --tag "bibliotheca-go:app-$TAG" .
      - docker build -f deployments/Dockerfile --target migration --tag "bibliotheca-go:migration-$TAG" .
    env:
      TAG: "{{default .GIT_COMMIT .TAG}}"

  run:
    cmds:
      - go run cmd/bibliotheca/main.go

  migrate:
    cmds:
      - ./scripts/migrate.sh up

  fmt:
    desc: Format the all go codes.
    cmds:
      - go fmt ./...

  dc-up:
    desc: Run the application in docker containers.
    deps: [dc-build]
    cmds:
      - docker-compose up -d db api

  dc-build:
    desc: Build the docker-compose's containers.
    cmds:
      - docker-compose build

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
