// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("BookShelves", testBookShelves)
	t.Run("Books", testBooks)
	t.Run("Groups", testGroups)
	t.Run("Users", testUsers)
}

func TestDelete(t *testing.T) {
	t.Run("BookShelves", testBookShelvesDelete)
	t.Run("Books", testBooksDelete)
	t.Run("Groups", testGroupsDelete)
	t.Run("Users", testUsersDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("BookShelves", testBookShelvesQueryDeleteAll)
	t.Run("Books", testBooksQueryDeleteAll)
	t.Run("Groups", testGroupsQueryDeleteAll)
	t.Run("Users", testUsersQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("BookShelves", testBookShelvesSliceDeleteAll)
	t.Run("Books", testBooksSliceDeleteAll)
	t.Run("Groups", testGroupsSliceDeleteAll)
	t.Run("Users", testUsersSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("BookShelves", testBookShelvesExists)
	t.Run("Books", testBooksExists)
	t.Run("Groups", testGroupsExists)
	t.Run("Users", testUsersExists)
}

func TestFind(t *testing.T) {
	t.Run("BookShelves", testBookShelvesFind)
	t.Run("Books", testBooksFind)
	t.Run("Groups", testGroupsFind)
	t.Run("Users", testUsersFind)
}

func TestBind(t *testing.T) {
	t.Run("BookShelves", testBookShelvesBind)
	t.Run("Books", testBooksBind)
	t.Run("Groups", testGroupsBind)
	t.Run("Users", testUsersBind)
}

func TestOne(t *testing.T) {
	t.Run("BookShelves", testBookShelvesOne)
	t.Run("Books", testBooksOne)
	t.Run("Groups", testGroupsOne)
	t.Run("Users", testUsersOne)
}

func TestAll(t *testing.T) {
	t.Run("BookShelves", testBookShelvesAll)
	t.Run("Books", testBooksAll)
	t.Run("Groups", testGroupsAll)
	t.Run("Users", testUsersAll)
}

func TestCount(t *testing.T) {
	t.Run("BookShelves", testBookShelvesCount)
	t.Run("Books", testBooksCount)
	t.Run("Groups", testGroupsCount)
	t.Run("Users", testUsersCount)
}

func TestHooks(t *testing.T) {
	t.Run("BookShelves", testBookShelvesHooks)
	t.Run("Books", testBooksHooks)
	t.Run("Groups", testGroupsHooks)
	t.Run("Users", testUsersHooks)
}

func TestInsert(t *testing.T) {
	t.Run("BookShelves", testBookShelvesInsert)
	t.Run("BookShelves", testBookShelvesInsertWhitelist)
	t.Run("Books", testBooksInsert)
	t.Run("Books", testBooksInsertWhitelist)
	t.Run("Groups", testGroupsInsert)
	t.Run("Groups", testGroupsInsertWhitelist)
	t.Run("Users", testUsersInsert)
	t.Run("Users", testUsersInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("BookShelfToGroupUsingGroup", testBookShelfToOneGroupUsingGroup)
	t.Run("BookToBookShelfUsingBookShelf", testBookToOneBookShelfUsingBookShelf)
	t.Run("BookToUserUsingBorrowedBy", testBookToOneUserUsingBorrowedBy)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("BookShelfToBooks", testBookShelfToManyBooks)
	t.Run("GroupToBookShelves", testGroupToManyBookShelves)
	t.Run("GroupToUsers", testGroupToManyUsers)
	t.Run("UserToBorrowedByBooks", testUserToManyBorrowedByBooks)
	t.Run("UserToGroups", testUserToManyGroups)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("BookShelfToGroupUsingBookShelves", testBookShelfToOneSetOpGroupUsingGroup)
	t.Run("BookToBookShelfUsingBooks", testBookToOneSetOpBookShelfUsingBookShelf)
	t.Run("BookToUserUsingBorrowedByBooks", testBookToOneSetOpUserUsingBorrowedBy)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {
	t.Run("BookToUserUsingBorrowedByBooks", testBookToOneRemoveOpUserUsingBorrowedBy)
}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("BookShelfToBooks", testBookShelfToManyAddOpBooks)
	t.Run("GroupToBookShelves", testGroupToManyAddOpBookShelves)
	t.Run("GroupToUsers", testGroupToManyAddOpUsers)
	t.Run("UserToBorrowedByBooks", testUserToManyAddOpBorrowedByBooks)
	t.Run("UserToGroups", testUserToManyAddOpGroups)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {
	t.Run("GroupToUsers", testGroupToManySetOpUsers)
	t.Run("UserToBorrowedByBooks", testUserToManySetOpBorrowedByBooks)
	t.Run("UserToGroups", testUserToManySetOpGroups)
}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {
	t.Run("GroupToUsers", testGroupToManyRemoveOpUsers)
	t.Run("UserToBorrowedByBooks", testUserToManyRemoveOpBorrowedByBooks)
	t.Run("UserToGroups", testUserToManyRemoveOpGroups)
}

func TestReload(t *testing.T) {
	t.Run("BookShelves", testBookShelvesReload)
	t.Run("Books", testBooksReload)
	t.Run("Groups", testGroupsReload)
	t.Run("Users", testUsersReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("BookShelves", testBookShelvesReloadAll)
	t.Run("Books", testBooksReloadAll)
	t.Run("Groups", testGroupsReloadAll)
	t.Run("Users", testUsersReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("BookShelves", testBookShelvesSelect)
	t.Run("Books", testBooksSelect)
	t.Run("Groups", testGroupsSelect)
	t.Run("Users", testUsersSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("BookShelves", testBookShelvesUpdate)
	t.Run("Books", testBooksUpdate)
	t.Run("Groups", testGroupsUpdate)
	t.Run("Users", testUsersUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("BookShelves", testBookShelvesSliceUpdateAll)
	t.Run("Books", testBooksSliceUpdateAll)
	t.Run("Groups", testGroupsSliceUpdateAll)
	t.Run("Users", testUsersSliceUpdateAll)
}
