// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	BookShelves          string
	Books                string
	Groups               string
	UserGroupMemberships string
	Users                string
}{
	BookShelves:          "book_shelves",
	Books:                "books",
	Groups:               "groups",
	UserGroupMemberships: "user_group_memberships",
	Users:                "users",
}
