// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("BookShelves", testBookShelvesUpsert)

	t.Run("Books", testBooksUpsert)

	t.Run("Groups", testGroupsUpsert)

	t.Run("Users", testUsersUpsert)
}
