#!/usr/bin/env bash

set -e -o pipefail

cd `dirname $0`

function echo_header() {
  cat <<EOF
-- This file was generated by $(basename $0).
-- DO NOT MANUALLY MODIFY THIS.

EOF
}

function dump_schema() {
  pg_dump $APP_DB_URL \
        --schema public \
        --exclude-table schema_migrations \
        --no-owner \
        --schema-only \
        --no-privileges \
    | grep -v \
        -e '^--' \
        -e '^SET ' \
        -e '^SELECT ' \
        -e '^CREATE SCHEMA ' \
        -e '^COMMENT ON SCHEMA ' \
    | # remove public schema prefix
      sed 's/public\.//g' \
    | # remove adjacent line breaks
      cat -s \
    | # remove line break on top of the file
      tail -n+2
}

function main() {
  local tempschema="$(mktemp /tmp/pg_schema.XXXXX.sql)"
  trap "[[ -f '$tempschema' ]] && rm $tempschema" EXIT

  echo_header >> "$tempschema"
  dump_schema >> "$tempschema"

  mv -f "$tempschema" schema.sql
}

main
