-- This file was generated by dump_schema.sh.
-- DO NOT MANUALLY MODIFY THIS.

CREATE DOMAIN ulid AS character varying(26);

CREATE TABLE books (
    book_id ulid NOT NULL,
    bookshelf_id ulid NOT NULL,
    title character varying(128) NOT NULL,
    borrowed_by ulid,
    isbn character varying(64),
    updated_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL
);

CREATE TABLE bookshelves (
    bookshelf_id ulid NOT NULL,
    group_id ulid NOT NULL,
    name character varying(128) NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL
);

CREATE TABLE groups (
    group_id ulid NOT NULL,
    name character varying(128) NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL
);

CREATE TABLE user_group_memberships (
    user_id ulid NOT NULL,
    group_id ulid NOT NULL
);

CREATE TABLE users (
    user_id ulid NOT NULL,
    name character varying(128) NOT NULL,
    email character varying(128) NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL
);

ALTER TABLE ONLY books
    ADD CONSTRAINT books_pkey PRIMARY KEY (book_id);

ALTER TABLE ONLY bookshelves
    ADD CONSTRAINT bookshelves_pkey PRIMARY KEY (bookshelf_id);

ALTER TABLE ONLY groups
    ADD CONSTRAINT groups_pkey PRIMARY KEY (group_id);

ALTER TABLE ONLY user_group_memberships
    ADD CONSTRAINT user_group_memberships_pkey PRIMARY KEY (user_id, group_id);

ALTER TABLE ONLY users
    ADD CONSTRAINT users_email_key UNIQUE (email);

ALTER TABLE ONLY users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);

ALTER TABLE ONLY books
    ADD CONSTRAINT books_bookshelf_id_fkey FOREIGN KEY (bookshelf_id) REFERENCES bookshelves(bookshelf_id) ON DELETE CASCADE;

ALTER TABLE ONLY books
    ADD CONSTRAINT books_borrowed_by_fkey FOREIGN KEY (borrowed_by) REFERENCES users(user_id) ON DELETE SET NULL;

ALTER TABLE ONLY bookshelves
    ADD CONSTRAINT bookshelves_group_id_fkey FOREIGN KEY (group_id) REFERENCES groups(group_id) ON DELETE CASCADE;

ALTER TABLE ONLY user_group_memberships
    ADD CONSTRAINT user_group_memberships_group_id_fkey FOREIGN KEY (group_id) REFERENCES groups(group_id) ON DELETE CASCADE;

ALTER TABLE ONLY user_group_memberships
    ADD CONSTRAINT user_group_memberships_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE;

